package com.binance.api.client.domain.account.request

import com.binance.api.client.constant.BinanceApiConstants
import org.apache.commons.lang3.builder.ToStringBuilder

/**
 * Request object for canceling an order.
 */
class CancelOrderRequest : OrderRequest {
    var orderId: Long? = null
        private set
    var origClientOrderId: String? = null
        private set

    constructor(symbol: String, orderId: Long?) : super(symbol) {
        this.orderId = orderId
    }

    constructor(symbol: String, origClientOrderId: String?) : super(symbol) {
        this.origClientOrderId = origClientOrderId
    }

    /**
     * Used to uniquely identify this cancel. Automatically generated by default.
     */
    var newClientOrderId: String? = null
        private set

    fun orderId(orderId: Long?): CancelOrderRequest {
        this.orderId = orderId
        return this
    }

    fun origClientOrderId(origClientOrderId: String?): CancelOrderRequest {
        this.origClientOrderId = origClientOrderId
        return this
    }

    fun newClientOrderId(newClientOrderId: String?): CancelOrderRequest {
        this.newClientOrderId = newClientOrderId
        return this
    }

    override fun toString(): String {
        return ToStringBuilder(this, BinanceApiConstants.TO_STRING_BUILDER_STYLE)
                .append("orderId", orderId)
                .append("origClientOrderId", origClientOrderId)
                .append("newClientOrderId", newClientOrderId)
                .toString()
    }
}